language: node_js

node_js:
  - "9"

dist: trusty

sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless

before_deploy:
  - npm install netlify-cli -g
  - npm run build --prod

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master