language: node_js

node_js:
  - "10.16.0"

cache:
  yarn: true
  directories:
    - node_modules

dist: trusty

sudo: required

branches:
  only:
  - master

before_script:
  - yarn global add @angular/cli

script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless

before_deploy:
  - yarn global add netlify-cli
  - ng build --prod

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  skip_cleanup: true
  on:
    branch: master